package com.innernest.decor.order;

public enum OrderStatus {
  PLACED,
  PROCESSING,
  SHIPPED,
  DELIVERED,
  CANCELLATION_REQUESTED,
  CANCELLED,
  RETURN_REQUESTED,
  RETURN_APPROVED,
  RETURN_REJECTED,
  RETURNED
}
